# Generated by Django 5.0.2 on 2024-05-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttracker', '0002_remove_employeurtask_employeur_remove_task_employeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Poste', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
                'db_table': 'employeur',
                'ordering': ['Username'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Titre', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('Employeur', models.ManyToManyField(to='ttracker.employeur')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('NbrPenalite', models.IntegerField()),
                ('DatePenalite', models.DateField()),
                ('Employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttracker.employeur')),
                ('Task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ttracker.task')),
            ],
            options={
                'db_table': 'penalites',
            },
        ),
        migrations.CreateModel(
            name='EmployeurTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttracker.employeur')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttracker.task')),
            ],
        ),
    ]
