# Generated by Django 5.0.2 on 2024-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttracker', '0004_alter_user_is_admin_alter_user_is_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
