# Generated by Django 5.0.2 on 2024-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttracker', '0005_alter_employeur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
